import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/.tsbuildinfo',
      '**/*.tsbuildinfo',
      // Replit-managed skill templates and scratch space. Git-ignored, and flat
      // config does not read .gitignore.
      '.local/**',
      '.agents/**',
      '.cache/**',
      'attached_assets/**',
      // Generated by Orval from lib/api-spec/openapi.yaml — edit the spec instead.
      'lib/api-client-react/src/generated/**',
      'lib/api-zod/src/generated/**',
      'lib/db/migrations/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    rules: {
      // Underscore prefix is the workspace convention for intentionally unused
      // bindings (Express middleware signatures rely on it heavily).
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': 'warn',
      'no-implicit-coercion': 'error',
      'prefer-const': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
    },
  },

  // Frontend applications
  {
    files: ['artifacts/ckbhse-website/**/*.{ts,tsx}'],
    languageOptions: {
      globals: globals.browser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
    },
  },

  // shadcn/ui primitives and their companion hooks are vendored upstream code.
  // They stay linted for genuine faults (undefined variables, unreachable code)
  // but are exempted from stylistic and React-idiom rules that would otherwise
  // require re-patching every file on each `shadcn add`.
  {
    files: [
      '**/components/ui/**/*.tsx',
      'lib/ui/src/components/**/*.tsx',
      '**/hooks/use-mobile.tsx',
      '**/hooks/use-toast.ts',
      'lib/ui/src/hooks/**',
    ],
    rules: {
      'react-refresh/only-export-components': 'off',
      '@typescript-eslint/consistent-type-imports': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      'no-implicit-coercion': 'off',
      '@typescript-eslint/no-unused-vars': 'warn',
      // Upstream uses Math.random for skeleton widths and synchronous setState
      // in media-query effects. Both are deliberate in that context.
      'react-hooks/purity': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },

  // Node-side code
  {
    files: [
      'artifacts/api-server/**/*.ts',
      'lib/db/**/*.ts',
      'lib/platform/**/*.ts',
      'scripts/**/*.{ts,mjs}',
      '**/*.config.{ts,mjs}',
      '**/build.mjs',
    ],
    languageOptions: { globals: globals.node },
  },

  // Tooling and scripts legitimately write to stdout.
  {
    files: [
      'scripts/**',
      '**/build.mjs',
      '**/*.config.{ts,mjs}',
      'lib/db/src/migrate.ts',
      'artifacts/api-server/src/config/env.ts',
    ],
    rules: { 'no-console': 'off' },
  },

  prettier,
);
